### ISSUE TITLE
No support for `transient` variable- you get Error: extraneous input 

### ISSUE THREAD

**Issue by oveddan** [prettier-solidity/prettier-plugin-solidity#1078]
newer versions of solidity support transient storage:

```solidity
contract MyContract {
   bool transient isRunning;
}
```

but with prettier-plugin-solidity you get an error:

checking formatting...
src/Cointag.sol
[error] src/Cointag.sol: Error: extraneous input 'isRunning' expecting {';', '='} (33:19)
[error]     at Object.parse (/node_modules/.pnpm/@solidity-parser+parser@0.18.0/node_modules/@solidity-parser/parser/dist/index.cjs.js:38775:13)
[error]     at Object.parse (node_modules/.pnpm/prettier-plugin-solidity@1.4.1_prettier@3.3.3/node_modules/prettier-plugin-solidity/src/parser.js:18:25)

**Comment by oveddan** [comment]
can be solved by bumping to the latest version of solidity parser: https://github.com/solidity-parser/parser/pull/119

**Comment by Janther** [comment]
I made a commit for this and we will release a patch soon.

In the meantime this has already been implemented in our [next](https://github.com/prettier-solidity/prettier-plugin-solidity/releases/tag/v2.0.0-beta.5) release which is already in the release candidate stages and use `slang-solidity` instead of `solidity-parse`.

**Comment by Janther** [comment]
Thank you @oveddan. We just published a new version with support for this.
