### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by avatar-lavventura** [prettier-solidity/prettier-plugin-solidity#249]
`prettier-plugin-solidity` get confused for one liner `if` or `else` when I have a comment line under it:

In following cases:

`{}` is missing for if.
```
	if (_value > 0)
	else {
	}
```

and

comment under one liner if without `{}`
```
        if (_providerPriceBlockIndex > block.number)
            // comment
            _providerPriceBlockIndex = providerInfo[providerInfo.length - 2];
```
and bracket for else is missing even its correct way

```
else 
 	// comment
       if (storageInfo.received == 0)
           cacheCost = cacheCost.add(info.priceCache.mul(dataTransferIn[i])); // cacheCost
```                    

-------------

I get following error:
```
[error] contracts/eB.sol: TypeError: Cannot read property 'filter' of undefined
[error]     at addBlockStatementFirstComment (/Users/alper/eBlocBroker/node_modules/prettier-plugin-solidity/src/prettier-comments/language-js/comments.js:186:26)
[error]     at handleIfStatementComments (/Users/alper/eBlocBroker/node_modules/prettier-plugin-solidity/src/prettier-comments/language-js/comments.js:265:5)
[error]     at handleEndOfLineComment (/Users/alper/eBlocBroker/node_modules/prettier-plugin-solidity/src/prettier-comments/language-js/comments.js:98:5)
[error]     at solidityHandleEndOfLineComment (/Users/alper/eBlocBroker/node_modules/prettier-plugin-solidity/src/comments/handler.js:55:5)
[error]     at /Users/alper/eBlocBroker/node_modules/prettier/bin-prettier.js:12427:11
[error]     at Array.forEach (<anonymous>)
[error]     at Object.attach (/Users/alper/eBlocBroker/node_modules/prettier/bin-prettier.js:12380:12)
[error]     at attachComments (/Users/alper/eBlocBroker/node_modules/prettier/bin-prettier.js:13241:14)
[error]     at coreFormat (/Users/alper/eBlocBroker/node_modules/prettier/bin-prettier.js:13270:21)
[error]     at format (/Users/alper/eBlocBroker/node_modules/prettier/bin-prettier.js:13516:73)
```

**Comment by fvictorio** [comment]
```
	if (_value > 0)
	else {
	}
```

is this valis Solidity syntax? It doesn't compile in Remix.

**Comment by avatar-lavventura** [comment]
I forget to add its line, `if` has only one line:

```
if (_value > 0)
    x = 1;
else {
}
```

**Comment by Janther** [comment]
I'm tackling the `IfStatement` comments rules and am still not quite happy with the coices, I'll be offline for a week or so I welcome anybody that wants to help.

just have a look at [feature/if_statement_comments](https://github.com/prettier-solidity/prettier-plugin-solidity/tree/feature/if_statement_comments)
