### ISSUE TITLE
new call syntax not supported

### ISSUE THREAD

**Issue by wighawag** [prettier-solidity/prettier-plugin-solidity#260]
the following code :
```
testContract.test{value:msg.value}();
```

result in the following error : 

```
line 32:30 no viable alternative at input 'testContract.test{'
line 32:36 no viable alternative at input 'value:'
Error: Unknown type: "NameValueExpression"
    at Object.genericPrint [as print] (C:\dev\projects\test\contracts\node_modules\prettier-plugin-solidity\src\printer.js:11:11)
    at callPluginPrintFunction (C:\dev\projects\test\contracts\node_modules\prettier\index.js:14571:18)
    at C:\dev\projects\test\contracts\node_modules\prettier\index.js:14521:47
    at Object.printComments (C:\dev\projects\test\contracts\node_modules\prettier\index.js:14194:19)
    at printGenerically (C:\dev\projects\test\contracts\node_modules\prettier\index.js:14521:22)
    at FastPath.call (C:\dev\projects\test\contracts\node_modules\prettier\index.js:14314:20)
    at Object.print (C:\dev\projects\test\contracts\node_modules\prettier-plugin-solidity\src\nodes\FunctionCall.js:36:12)
    at Object.genericPrint [as print] (C:\dev\projects\test\contracts\node_modules\prettier-plugin-solidity\src\printer.js:21:27)
    at callPluginPrintFunction (C:\dev\projects\test\contracts\node_modules\prettier\index.js:14571:18)
    at C:\dev\projects\test\contracts\node_modules\prettier\index.js:14521:47
error Command failed with exit code 1.
```

**Comment by fvictorio** [comment]
This is supported by the new parser but we haven't added the formatting rules for this node. Thanks for reporting it!

**Comment by fvictorio** [comment]
This is working in the latest version.
