### ISSUE TITLE
Comment before else is not printed

### ISSUE THREAD

**Issue by wighawag** [prettier-solidity/prettier-plugin-solidity#328]
I get the following error:

```
contracts\DiamondFacet.sol
[error] contracts\DiamondFacet.sol: Error: Comment "replace" was not printed. Please report this error!
[error]     at C:\dev\projects\wighawag\Diamond\node_modules\prettier\index.js:14273:13
[error]     at Array.forEach (<anonymous>)
[error]     at Object.ensureAllCommentsPrinted (C:\dev\projects\wighawag\Diamond\node_modules\prettier\index.js:14271:15)
[error]     at coreFormat (C:\dev\projects\wighawag\Diamond\node_modules\prettier\index.js:14858:12)
[error]     at format (C:\dev\projects\wighawag\Diamond\node_modules\prettier\index.js:15063:14)
[error]     at formatWithCursor (C:\dev\projects\wighawag\Diamond\node_modules\prettier\index.js:15080:12)
[error]     at Object.formatWithCursor (C:\dev\projects\wighawag\Diamond\node_modules\prettier\index.js:54672:12)
[error]     at format (C:\dev\projects\wighawag\Diamond\node_modules\prettier\bin-prettier.js:15851:14)
[error]     at Object.formatFiles (C:\dev\projects\wighawag\Diamond\node_modules\prettier\bin-prettier.js:16035:16)
[error]     at Object.run (C:\dev\projects\wighawag\Diamond\node_modules\prettier\bin-prettier.js:16508:14)
```

It might be related to https://github.com/prettier-solidity/prettier-plugin-solidity/issues/327 as it happens in the same compilation:

Here is the repo to reproduce it : https://github.com/wighawag/Diamond/tree/prettier (branch prettier)

```
npm i
npm run prettier
```

**Comment by fvictorio** [comment]
Hey Ronan, thanks for opening this and the previous issue.

This is probably not related to #327. We just have a lot of issues around comments. @Janther is the expert on this.

As a workwaround, you can try moving the comment (inside the `else`, maybe?) and see if it works after that.

**Comment by wighawag** [comment]
Thanks @fvictorio got it working with the new version and moving the comment

**Comment by fvictorio** [comment]
Reproduction:

```solidity
contract Foo {
  function foo() public {
    if (condition) {
      something();
    }
    // comment
    else {
      somethingElse();
    }
  }
}
```
