### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by mattiaerre** [prettier-solidity/prettier-plugin-solidity#35]
# Description

## How to reproduce

Run the plugin against the following contract

```solidity
/*
	This is a very simple demonstration of a while loops. Same as JS/c.
*/

contract BasicIterator {

    address creator;                  // reserve one "address"-type spot
    uint8[10] integers;               // reserve a chunk of storage for 10 8-bit unsigned integers in an array

    function BasicIterator() 
    {
        creator = msg.sender;         // set the creator address
        uint8 x = 0;                  // initialize an 8-bit, unsigned integer to zero
        while(x < integers.length)    // the variable integers was initialized to length 10
        {
        	integers[x] = x;      // set integers to [0,1,2,3,4,5,6,7,8,9] over ten iterations
        	x++;
        }
    }
    
    function getSum() constant returns (uint)  // "constant" just means this function returns something to the caller
    {                                          // which is immediately followed by what type gets returned, in this case a full uint256
    	uint8 sum = 0;
    	uint8 x = 0;
    	while(x < integers.length)
        {
        	sum = sum + integers[x];
        	x++;
        }
    	return sum;
    }
    
    /**********
     Standard kill() function to recover funds 
     **********/
    
    function kill()
    { 
        if (msg.sender == creator)
        {
            suicide(creator);  // kills this contract and sends remaining funds back to creator
        }
    }
}
```

[contract's source](https://github.com/fivedogit/solidity-baby-steps/blob/master/contracts/08_basiciterator.sol)

## Stack trace

```bash
[error] contracts/08_basiciterator.sol: TypeError: Cannot read property 'type' of undefined
[error]     at propagateBreaksOnEnterFn (/Users/mrichetto/projects/solidity-baby-steps/node_modules/prettier/bin-prettier.js:9195:13)
[error]     at traverseDoc (/Users/mrichetto/projects/solidity-baby-steps/node_modules/prettier/bin-prettier.js:9053:11)
[error]     at Object.propagateBreaks (/Users/mrichetto/projects/solidity-baby-steps/node_modules/prettier/bin-prettier.js:9220:3)
[error]     at printAstToDoc (/Users/mrichetto/projects/solidity-baby-steps/node_modules/prettier/bin-prettier.js:10095:14)
[error]     at coreFormat (/Users/mrichetto/projects/solidity-baby-steps/node_modules/prettier/bin-prettier.js:10414:16)
[error]     at format (/Users/mrichetto/projects/solidity-baby-steps/node_modules/prettier/bin-prettier.js:10572:16)
[error]     at formatWithCursor (/Users/mrichetto/projects/solidity-baby-steps/node_modules/prettier/bin-prettier.js:10584:12)
[error]     at Object.formatWithCursor (/Users/mrichetto/projects/solidity-baby-steps/node_modules/prettier/bin-prettier.js:34926:15)
[error]     at format$1 (/Users/mrichetto/projects/solidity-baby-steps/node_modules/prettier/bin-prettier.js:36846:21)
[error]     at /Users/mrichetto/projects/solidity-baby-steps/node_modules/prettier/bin-prettier.js:37035:16
```

**Comment by fvictorio** [comment]
I think the problem is here:

https://github.com/prettier-solidity/prettier-plugin-solidity/blob/7a4d4bd2385262eb21c28ac1fbc4bd4196b4f9fd/src/printer.js#L258-L261

When you are parsing the parameter list of an event, you don't have a `visibility`, so the join gets an undefined value. I'm not sure if this is a problem with the parser or just how it's meant to be. A possible fix is to change that condition for `if (!node.visibility || node.visibility === 'default')`. That fixes the problem, but I'm not sure if it's the right solution.
