### ISSUE TITLE
Error with the fallback function

### ISSUE THREAD

**Issue by julien-h** [prettier-solidity/prettier-plugin-solidity#431]
Unable to format code with a [fallback function](https://docs.soliditylang.org/en/latest/contracts.html#fallback-function):

Code: `contracts/Fallback.sol`:

```
pragma solidity 0.8.0;

contract Fallback {
    fallback (bytes calldata _input) external returns (bytes memory _output) {
        
    }
}
```

Command: 
```
npx prettier contracts/Fallback.sol
```

Error:
```
$ npx prettier contracts/Fallback.sol 
contracts/Fallback.sol[error] contracts/Fallback.sol: Error: Fallback functions cannot have parameters
[error]     at ASTBuilder.FunctionDefinition (/home/julien/src/solidity-gas-optimizations/node_modules/@solidity-parser/parser/dist/index.cjs.js:25509:17)
[error]     at ASTBuilder.visit (/home/julien/src/solidity-gas-optimizations/node_modules/@solidity-parser/parser/dist/index.cjs.js:26804:42)
[error]     at ASTBuilder.ContractPart (/home/julien/src/solidity-gas-optimizations/node_modules/@solidity-parser/parser/dist/index.cjs.js:25458:17)
[error]     at ASTBuilder.visit (/home/julien/src/solidity-gas-optimizations/node_modules/@solidity-parser/parser/dist/index.cjs.js:26804:42)
[error]     at ASTBuilder.<anonymous> (/home/julien/src/solidity-gas-optimizations/node_modules/@solidity-parser/parser/dist/index.cjs.js:26789:26)
[error]     at Array.map (<anonymous>)
[error]     at ASTBuilder.visit (/home/julien/src/solidity-gas-optimizations/node_modules/@solidity-parser/parser/dist/index.cjs.js:26788:20)
[error]     at ASTBuilder.ContractDefinition (/home/julien/src/solidity-gas-optimizations/node_modules/@solidity-parser/parser/dist/index.cjs.js:25445:22)
[error]     at ASTBuilder.visit (/home/julien/src/solidity-gas-optimizations/node_modules/@solidity-parser/parser/dist/index.cjs.js:26804:42)
[error]     at ASTBuilder.<anonymous> (/home/julien/src/solidity-gas-optimizations/node_modules/@solidity-parser/parser/dist/index.cjs.js:26789:26)
```

Version: 
```
$ npx prettier --version
2.2.1
```

**Comment by mattiaerre** [comment]
thanks for reporting this issue @julien-h

**Comment by fvictorio** [comment]
This seems to have been fixed in the latest versions. Thanks for reporting @julien-h!
