### ISSUE TITLE
Error with array slices

### ISSUE THREAD

**Issue by julien-h** [prettier-solidity/prettier-plugin-solidity#432]
Unable to format code with [Array slices](https://docs.soliditylang.org/en/latest/types.html#array-slices).

Code: (file `contracts/Test.sol`)

```
pragma solidity 0.8.1;

contract Test {
    function a(bytes calldata x) public pure {
        address y = abi.decode(x[4:], (address));
        b(y);
    }
    function b(address y) private pure {

    }
}
```

Compilation is fine:
```
$solc --bin --abi contracts/Test.sol -o build --overwrite
Compiler run successful. Artifact(s) can be found in directory build.
```

Error with prettier:
```
$ npx prettier contracts/Test.sol
contracts/Test.sol[error] contracts/Test.sol: TypeError: Cannot read property 'type' of undefined
[error]     at Object.genericPrint [as print] (/home/julien/src/solidity-gas-optimizations/node_modules/prettier-plugin-solidity/src/printer.js:10:14)
[error]     at callPluginPrintFunction (/home/julien/src/solidity-gas-optimizations/node_modules/prettier/index.js:14718:18)
[error]     at comments.printComments.p (/home/julien/src/solidity-gas-optimizations/node_modules/prettier/index.js:14649:47)
[error]     at Object.printComments (/home/julien/src/solidity-gas-optimizations/node_modules/prettier/index.js:14305:19)
[error]     at printGenerically (/home/julien/src/solidity-gas-optimizations/node_modules/prettier/index.js:14649:22)
[error]     at FastPath.call (/home/julien/src/solidity-gas-optimizations/node_modules/prettier/index.js:14441:20)
[error]     at Object.print (/home/julien/src/solidity-gas-optimizations/node_modules/prettier-plugin-solidity/src/nodes/IndexRangeAccess.js:14:12)
[error]     at Object.genericPrint [as print] (/home/julien/src/solidity-gas-optimizations/node_modules/prettier-plugin-solidity/src/printer.js:21:27)
[error]     at callPluginPrintFunction (/home/julien/src/solidity-gas-optimizations/node_modules/prettier/index.js:14718:18)
[error]     at comments.printComments.p (/home/julien/src/solidity-gas-optimizations/node_modules/prettier/index.js:14649:47)
```

Version:
```
$npx prettier --version
2.2.1
```

**Comment by benkostr** [comment]
The temporary workaround is to use explicit indexes. e.g. Use `x[4:x.length]` instead of `x[4:]`

**Comment by fvictorio** [comment]
> The temporary workaround is to use explicit indexes. e.g. Use `x[4:x.length]` instead of `x[4:]`

Ugh, that's lame, I'll try to have this fixed asap, sorry for taking so long.
