### ISSUE TITLE
Error: Unknown type: "RevertStatement"

### ISSUE THREAD

**Issue by paulrberg** [prettier-solidity/prettier-plugin-solidity#545]
I am using v0.8.4 custom errors in my project, which are perhaps the cause for this prettier error:

```
Error: Unknown type: "RevertStatement"
	at Object.genericPrint [as print] (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/printer.js:12:11)
	at callPluginPrintFunction (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16169:21)
	at mainPrintInternal (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16107:17)
	at mainPrint (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16089:14)
	at /Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/print-preserving-empty-lines.js:33:16
	at AstPath.each (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:15864:7)
	at printPreservingEmptyLines (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/print-preserving-empty-lines.js:10:8)
	at Object.print (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/Block.js:20:15)
	at Object.genericPrint [as print] (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/printer.js:24:27)
	at callPluginPrintFunction (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16169:21)
	at mainPrintInternal (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16107:17)
	at mainPrint (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16089:14)
	at AstPath.call (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:15831:20)
	at printTrueBody (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/IfStatement.js:12:30)
	at Object.print (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/IfStatement.js:53:16)
	at Object.genericPrint [as print] (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/printer.js:24:27)
	at callPluginPrintFunction (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16169:21)
	at mainPrintInternal (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16107:17)
	at mainPrint (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16089:14)
	at /Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/print-preserving-empty-lines.js:33:16
	at AstPath.each (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:15864:7)
	at printPreservingEmptyLines (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/print-preserving-empty-lines.js:10:8)
	at Object.print (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/Block.js:20:15)
	at Object.genericPrint [as print] (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/printer.js:24:27)
	at callPluginPrintFunction (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16169:21)
	at mainPrintInternal (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16107:17)
	at mainPrint (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16089:14)
	at AstPath.call (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:15831:20)
	at Object.print (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/UncheckedStatement.js:9:38)
	at Object.genericPrint [as print] (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/printer.js:24:27)
	at callPluginPrintFunction (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16169:21)
	at mainPrintInternal (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16107:17)
	at mainPrint (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16089:14)
	at /Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/print-preserving-empty-lines.js:33:16
	at AstPath.each (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:15864:7)
	at printPreservingEmptyLines (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/print-preserving-empty-lines.js:10:8)
	at Object.print (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/Block.js:20:15)
	at Object.genericPrint [as print] (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/printer.js:24:27)
	at callPluginPrintFunction (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16169:21)
	at mainPrintInternal (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16107:17)
	at mainPrint (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16089:14)
	at AstPath.call (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:15831:20)
	at body (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/FunctionDefinition.js:101:55)
	at Object.print (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/FunctionDefinition.js:125:7)
	at Object.genericPrint [as print] (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/printer.js:24:27)
	at callPluginPrintFunction (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16169:21)
	at mainPrintInternal (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16107:17)
	at mainPrint (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16089:14)
	at /Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/print-preserving-empty-lines.js:33:16
	at AstPath.each (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:15864:7)
	at printPreservingEmptyLines (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/print-preserving-empty-lines.js:10:8)
	at body (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/ContractDefinition.js:26:11)
	at Object.print (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/ContractDefinition.js:45:7)
	at Object.genericPrint [as print] (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/printer.js:24:27)
	at callPluginPrintFunction (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16169:21)
	at mainPrintInternal (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16107:17)
	at mainPrint (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16089:14)
	at /Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/print-preserving-empty-lines.js:33:16
	at AstPath.each (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:15864:7)
	at printPreservingEmptyLines (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/print-preserving-empty-lines.js:10:8)
	at Object.print (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/nodes/SourceUnit.js:11:13)
	at Object.genericPrint [as print] (/Users/paulrberg/projects/prb-math/node_modules/prettier-plugin-solidity/src/printer.js:24:27)
	at callPluginPrintFunction (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16169:21)
	at mainPrintInternal (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16107:17)
	at mainPrint (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16089:14)
	at printAstToDoc (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16076:13)
	at coreFormat (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16436:15)
	at formatWithCursor$1 (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:16665:14)
	at /Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:60922:12
	at Object.format (/Users/paulrberg/projects/prb-math/node_modules/prettier/index.js:60942:12)
	at t.default.<anonymous> (/Users/paulrberg/.vscode/extensions/esbenp.prettier-vscode-8.0.1/dist/extension.js:1:14555)
	at Generator.next (<anonymous>)
	at i (/Users/paulrberg/.vscode/extensions/esbenp.prettier-vscode-8.0.1/dist/extension.js:1:7003)
```

**Comment by Janther** [comment]
Hi @paulrberg,
what version of the plugin are you using?
support for custom errors was added in `v1.0.0-beta.11`

**Comment by Janther** [comment]
if you upgrade your version of the plugin, we also recommend to upgrade prettier to at least `v2.3.0` since we use some of the new features it provides.

**Comment by paulrberg** [comment]
Whoops, I was using `v1.0.0-beta.10`. Thanks, I can confirm that it works!
