### ISSUE TITLE
Unknown type: "AssemblyLocalDefinition"

### ISSUE THREAD

**Issue by roderik** [prettier-solidity/prettier-plugin-solidity#58]
Source file: https://github.com/Arachnid/solidity-stringutils/blob/master/src/strings.sol#L48

Line 48 has the assembly call that freaks out the parser. The same thing happens with my Proxy contracts.

```
[error] contracts/external/strings.sol: Error: Unknown type: "AssemblyLocalDefinition"
[error]     at Object.genericPrint [as print] (/Users/roderik/Development/solidity-mint/node_modules/prettier-plugin-solidity/src/printer.js:458:13)
[error]     at genericPrint (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10130:18)
[error]     at /Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10076:16
[error]     at Object.printComments (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:9838:17)
[error]     at printGenerically (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10075:22)
[error]     at FastPath.map (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10007:21)
[error]     at Object.genericPrint [as print] (/Users/roderik/Development/solidity-mint/node_modules/prettier-plugin-solidity/src/printer.js:427:25)
[error]     at genericPrint (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10130:18)
[error]     at /Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10076:16
[error]     at Object.printComments (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:9838:17)
```

**Comment by roderik** [comment]
Additional Assembly is missing

```
[error] contracts/utility/upgrading/Dispatcher.sol: Error: Unknown type: "AssemblyAssignment"
[error]     at Object.genericPrint [as print] (/Users/roderik/Development/solidity-mint/node_modules/prettier-plugin-solidity/src/printer.js:458:13)
[error]     at genericPrint (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10130:18)
[error]     at /Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10076:16
[error]     at Object.printComments (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:9838:17)
[error]     at printGenerically (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10075:22)
[error]     at FastPath.map (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10007:21)
[error]     at Object.genericPrint [as print] (/Users/roderik/Development/solidity-mint/node_modules/prettier-plugin-solidity/src/printer.js:427:25)
[error]     at genericPrint (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10130:18)
[error]     at /Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10076:16
[error]     at Object.printComments (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:9838:17)
```

**Comment by mattiaerre** [comment]
hi @roderik there is a WIP PR #61 that addresses this issue; any feedback is welcome. thanks

**Comment by mattiaerre** [comment]
hi @roderik FYI prettier-plugin-solidity@1.0.0-alpha.7 has just been published and should fix this issue
