### ISSUE TITLE
Can't handle stray commas in parameter list

### ISSUE THREAD

**Issue by axic** [prettier-solidity/prettier-plugin-solidity#585]
```solidity
contract C {
  function f(uint256 a,) external view {}
}
```

results in
```
$ prettier --write "contracts/**/*.sol"
contracts/a.sol
[error] contracts/a.sol: Error: Assertion error: unhandled type name case
[error]     at ASTBuilder.visitTypeName (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35664:11)
[error]     at ASTBuilder.visitParameter (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35499:22)
[error]     at ParameterContext.accept (/node_modules/@solidity-parser/parser/dist/index.cjs.js:32870:22)
[error]     at ASTBuilder.visit (/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
[error]     at /node_modules/@solidity-parser/parser/dist/index.cjs.js:35552:70
[error]     at Array.map (<anonymous>)
[error]     at ASTBuilder.visitFunctionDefinition (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35552:54)
[error]     at FunctionDefinitionContext.accept (/node_modules/@solidity-parser/parser/dist/index.cjs.js:32561:22)
[error]     at ASTBuilder.visit (/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
[error]     at ASTBuilder.visitContractPart (/node_modules/@solidity-parser/parser/dist/index.cjs.js:35334:17)
```

The same happens with return parameters:
```solidity
contract C {
    function f(uint256) external view returns (uint256,) {}
}
```

I see it probably is a shortcoming in the underlying library, but since @fvictorio is the maintainer of that and involved here, I thought it is good to raise it here (so that once it is fixed in the parser, the dependency needs to be bumped here).

**Comment by Janther** [comment]
As far as I know solidity doesn't support trailing commas

**Comment by mattiaerre** [comment]
> As far as I know solidity doesn't support trailing commas

it sounds like this is more a linting issue then
