### ISSUE TITLE
Invalid input (contract without name or body) causes unclear crash

### ISSUE THREAD

**Issue by axic** [prettier-solidity/prettier-plugin-solidity#587]
```solidity
contract
```
and
```solidity
interface
```

result in
```
[error] contracts/I.sol: Error: mismatched input '<EOF>' expecting {'from', 'error', 'calldata', 'revert', 'callback', 'leave', 'payable', 'constructor', 'receive', Identifier} (1:8)
[error]     at Object.parse (/node_modules/@solidity-parser/parser/dist/index.cjs.js:36867:11)
[error]     at Object.parse (/node_modules/prettier-plugin-solidity/src/parser.js:18:25)
[error]     at Object.parse$a [as parse] (/node_modules/prettier/index.js:12513:19)
[error]     at coreFormat (/node_modules/prettier/index.js:14044:16)
[error]     at formatWithCursor$1 (/node_modules/prettier/index.js:14284:14)
[error]     at Object.formatWithCursor (/node_modules/prettier/index.js:59304:12)
[error]     at format$1 (/node_modules/prettier/bin-prettier.js:16953:21)
[error]     at Object.formatFiles$1 [as formatFiles] (/node_modules/prettier/bin-prettier.js:17067:16)
[error]     at async main (/node_modules/prettier/bin-prettier.js:18925:5)
[error]     at async Object.run (/node_modules/prettier/bin-prettier.js:18868:5)
```

Again, reporting it here similarly to #585. I understand if there's an explicit goal to not try parsing something the compiler would complain about. I'll stop reporting it that is the case :)

**Comment by mattiaerre** [comment]
same as https://github.com/prettier-solidity/prettier-plugin-solidity/issues/586#issuecomment-926921836 what do you think @fvictorio @Janther ?

**Comment by fvictorio** [comment]
Prettier doesn't work if there are parsing errors. The same thing happens in js if you try to format this:

```js
function
```

I agree that the message sucks, but that's a problem in the parser. Since you already opened the relevant issues there (thanks!), I believe we can close this one. But anyone feel free to re-open if you disagree.
