### ISSUE TITLE
Unknown type: "FunctionTypeName"

### ISSUE THREAD

**Issue by roderik** [prettier-solidity/prettier-plugin-solidity#59]
I cannot share this contract atm but I assume it is this line:

```
pragma experimental ABIEncoderV2;
```

```
[error] contracts/provenance/statemachine/StateMachine.sol: Error: Unknown type: "FunctionTypeName"
[error]     at Object.genericPrint [as print] (/Users/roderik/Development/solidity-mint/node_modules/prettier-plugin-solidity/src/printer.js:458:13)
[error]     at genericPrint (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10130:18)
[error]     at /Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10076:16
[error]     at Object.printComments (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:9838:17)
[error]     at printGenerically (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10075:22)
[error]     at FastPath.call (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:9949:16)
[error]     at Object.genericPrint [as print] (/Users/roderik/Development/solidity-mint/node_modules/prettier-plugin-solidity/src/printer.js:300:14)
[error]     at genericPrint (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10130:18)
[error]     at /Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:10076:16
[error]     at Object.printComments (/Users/roderik/Development/solidity-mint/node_modules/prettier/bin-prettier.js:9838:17)
```

**Comment by mattiaerre** [comment]
hi @roderik would it be possible to have a simpler contract to be able to reproduce this issue? that will help us to fix the bug; thanks so much

**Comment by mattiaerre** [comment]
hi @roderik it is actually something like this

```javascript
function (uint, uint) returns(bool) a;
```

as per https://github.com/federicobond/solidity-parser-antlr/blob/master/test/ast.js#L326

**Comment by roderik** [comment]
Can I hit you up on email or social somewhere where i can send you a private message, that way I can share the contract.

**Comment by mattiaerre** [comment]
sure @roderik you can use mattia.richetto@gmail.com or my twitter @mattiaerre and DM me but I am pretty sure in the contract where you have this issue there is an anonymous function similar to the one I've added above

**Comment by mattiaerre** [comment]
hi @roderik there is the #67 PR that should address and fix this issue
