### ISSUE TITLE
can't have standalone comments in constructor

### ISSUE THREAD

**Issue by jaycenhorton** [prettier-solidity/prettier-plugin-solidity#62]
prettier does not like when I have a standalone comment in the body of a constructor (or any other function):

```solidity
 constructor() public setMsgFields {
    // This constructor will be used to test the creation via multi-sig wallet
  }
```

```
[error] @noridoteco/contracts/contracts/wallet/TestCalls.sol: Error: Comment "This constructor will be used to test the creation via multi-sig wallet" was not printed. Please report this error!
[error]     at /home/ubuntu/dev/nori/node_modules/prettier/bin-prettier.js:10371:13
[error]     at Array.forEach (<anonymous>)
[error]     at ensureAllCommentsPrinted (/home/ubuntu/dev/nori/node_modules/prettier/bin-prettier.js:10369:15)
[error]     at coreFormat (/home/ubuntu/dev/nori/node_modules/prettier/bin-prettier.js:10417:3)
[error]     at format (/home/ubuntu/dev/nori/node_modules/prettier/bin-prettier.js:10572:16)
[error]     at formatWithCursor (/home/ubuntu/dev/nori/node_modules/prettier/bin-prettier.js:10584:12)
[error]     at Object.formatWithCursor (/home/ubuntu/dev/nori/node_modules/prettier/bin-prettier.js:34926:15)
[error]     at format$1 (/home/ubuntu/dev/nori/node_modules/prettier/bin-prettier.js:36846:21)
[error]     at /home/ubuntu/dev/nori/node_modules/prettier/bin-prettier.js:37035:16
[error]     at /home/ubuntu/dev/nori/node_modules/prettier/bin-prettier.js:36981:14

```

Source [here](https://github.com/nori-dot-eco/contracts/blob/master/contracts/wallet/TestCalls.sol#L24)

**Comment by jaycenhorton** [comment]
oops, duplicate of #45
