### ISSUE TITLE
Error when formatting inline struct creation

### ISSUE THREAD

**Issue by Remscar** [prettier-solidity/prettier-plugin-solidity#680]
Given the solidity code:
```
// Setup purchase information for the root (0://) domain
    purchaseData[0] = DomainPurchaseData({
      prices: _rootPrices,
      // Protection in case a price for short domains is forgotten
      subdomainMintingEnabled: _rootPrices.short > 0,
      allowSubdomainsToMint: true,
      wasAllowedToSubdomainMintOnCreation: true
    });
  ```
  
Where `DomainPurchaseData` is a struct.
An error will occur:
```
contracts\controllers\DomainPurchaser.sol
[error] contracts\controllers\DomainPurchaser.sol: Error: Comment "Protection in case a price for short domains is forgotten" was not printed. Please report this error!
[error]     at Object.ensureAllCommentsPrinted (G:\zer0\zns\node_modules\prettier\index.js:8136:17)
[error]     at coreFormat (G:\zer0\zns\node_modules\prettier\index.js:8682:16)
[error]     at formatWithCursor2 (G:\zer0\zns\node_modules\prettier\index.js:8864:18)
[error]     at Object.formatWithCursor (G:\zer0\zns\node_modules\prettier\index.js:39174:12)
[error]     at format (G:\zer0\zns\node_modules\prettier\cli.js:12043:24)
[error]     at formatFiles2 (G:\zer0\zns\node_modules\prettier\cli.js:12122:20)
[error]     at async main (G:\zer0\zns\node_modules\prettier\cli.js:12327:5)
[error]     at async Object.run (G:\zer0\zns\node_modules\prettier\cli.js:12274:5)
```

Removing the comment "// Protection in case a price for short domains is forgotten" fixes this

**Comment by Janther** [comment]
I like this one, I'll check this one out this week probably with the next release will work :)
