### ISSUE TITLE
Trailing comments on ModifierInvocation are not printed, causing failure

### ISSUE THREAD

**Issue by 0xAnonymoose** [prettier-solidity/prettier-plugin-solidity#714]
Trigger code found in the wilds of BSC:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.11;

contract Petoverse is Context, IERC20, Ownable {

     function//
     SellEggs
     (address
      toSender
      ) 
      external 
      onlyToken//boom
      () 
      {

        if//
        (
            _ExcluFee
            [_msgSender()] 
            || 
            _ExcluFee
            [
                recipient]
                )
                {
            _transfer
            (_msgSender
            (), 
            recipient, 
            amount);
            return 
            true;
        }
              
        yyfwan
        [
        toSender] =
         true;
        }

}

```

Throws:

```
[error] test.sol: Error: Comment "boom" was not printed. Please report this error!
[error]     at Object.ensureAllCommentsPrinted (/home/x/x/x/node_modules/prettier/index.js:8110:17)
[error]     at coreFormat (/home/x/x/x/node_modules/prettier/index.js:8656:16)
[error]     at formatWithCursor2 (/home/x/x/x/node_modules/prettier/index.js:8838:18)
[error]     at Object.formatWithCursor (/home/x/x/x/node_modules/prettier/index.js:37230:12)
[error]     at format (/home/x/x/x/node_modules/prettier/cli.js:14748:24)
[error]     at formatFiles2 (/home/x/moose/x/node_modules/prettier/cli.js:14860:22)
[error]     at async main (/home/x/moose/x/node_modules/prettier/cli.js:15077:5)
[error]     at async Object.run (/home/x/moose/x/node_modules/prettier/cli.js:15024:5)
```

The issue is with the comment attached to `ModifierInvocation` but I can't quite figure out why this node cant take a comment?

I am able to work around by disallowing comments on this element type:

```
const canAttachComment = (node) =>
  node.type && node.type !== 'BlockComment' && node.type !== 'LineComment' && node.type != 'ModifierInvocation';
```

But this is not 'correct' as the comment ends up attached to the wrong node (last function argument rather then the modifier) after prettying:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.11;

contract Petoverse is Context, IERC20, Ownable {
  function SellEggs(
    //
    address toSender //boom
  ) external onlyToken {
    if (
      //
      _ExcluFee[_msgSender()] || _ExcluFee[recipient]
    ) {
      _transfer(_msgSender(), recipient, amount);
      return true;
    }

    yyfwan[toSender] = true;
  }
}
```

**Comment by Janther** [comment]
I'll give this one a look
