### ISSUE TITLE
Error: Cannot find module 'emoji-regex'

### ISSUE THREAD

**Issue by schmidsi** [prettier-solidity/prettier-plugin-solidity#74]
If I want to run prettier in my library, I get the following error:

```
$ yarn format
yarn run v1.12.3
$ prettier --write src/**/*.ts
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'emoji-regex'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/schmidsi/Development/@melonproject/protocol/node_modules/prettier-plugin-solidity/src/prettier-comments/common/util.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
```

It suppose that the error comes from this line of code:

https://github.com/prettier-solidity/prettier-plugin-solidity/blob/7e89009fbd88b9c7e861be125f056ac3eee4c9fa/src/prettier-comments/common/util.js#L4

A possible fix was to install 'emoji-regex' in the consuming project, but that is a bad work around. You could probably remove this dependency completely?

**Comment by mattiaerre** [comment]
hi @schmidsi v1.0.0-alpha.12 has just been published and this issue should be fixed; let us know if you notice other problems; we really value your feedback!

https://www.npmjs.com/package/prettier-plugin-solidity

**Comment by schmidsi** [comment]
Works!
